# -*- coding: utf-8 -*-
"""
Automatically generated by Colaboratory.

Original file is run in https://colab.research.google.com/
To run this code, 'Online Retail.xlsx' need to be uploaded in colab's repository path '/content'.
"""

import math
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

plt.style.use('seaborn')
sns.set(font_scale=1)


oln=pd.read_excel('/content/Online Retail.xlsx')

oln.head(5)

oln.info()

oln.describe()

oln.describe(include=np.object)

print("총 데이터 수: ", oln.shape[0]*oln.shape[1])
print("총 결측치 수: {} = 전체 데이터의 {:.2f}%".format(oln.isnull().sum().sum(), (oln.isnull().sum().sum()*100)/(oln.shape[0]*oln.shape[1])))
print("전체 국가 수: ", oln.Country.nunique())
print("전체 판매 물건 수: ", oln.Description.nunique())

oln.columns=oln.columns.str.lower()
oln.columns

oln.isnull().sum()

oln[oln.isnull().any(axis=1)]

oln1=oln.dropna()
oln1.info()
oln1.describe()

oln1['customerid']=oln1['customerid'].astype('int64')
oln1

oln1.info()

print(min(oln1['quantity']), max(oln1['quantity']))
print(min(oln1['unitprice']), max(oln1['unitprice']))

oln1 = oln1[oln1.quantity> 0]

print(min(oln1['quantity']), max(oln1['quantity']))

oln1['spent']=oln1['quantity']*oln1['unitprice']
oln1

oln1['year']=oln1['invoicedate'].dt.year
oln1['month']=oln1['invoicedate'].dt.month
oln1['day']=oln1['invoicedate'].dt.day
oln1['weekday']=oln1['invoicedate'].dt.weekday
oln1['hour']=oln1['invoicedate'].dt.hour
oln1

oln1.description.value_counts().head(10).plot.bar()

res1=oln1[['customerid', 'spent']].groupby(['customerid']).sum()
res1.sort_values('spent', ascending=False)

res1 = res1[(res1['spent'] > 0)]

print("가장 소비를 많이 한 고객번호: {}, 소비량: {:.2f}".format(int(res1['spent'].argmax()), res1['spent'].max()))
print("가장 소비를 적게 한 고객번호: {}, 소비량: {:.2f}".format(int(res1['spent'].argmin()), res1['spent'].min()))

f, ax = plt.subplots(1, 1, figsize=(5, 4), dpi=80)

sns.boxplot(oln1['unitprice'], showfliers=False, ax=ax)

ck1=oln1[oln1['unitprice'] <= 5].shape[0]/oln1['unitprice'].shape[0]*100
print("5 파운드 이하 상품 주문이 {:.2f} % 를 차지합니다.".format(ck1))

ck2=np.sum(oln1[oln1['unitprice'] <= 5].spent)/np.sum(oln1.spent)*100
print("5 파운드 이하 상품 주문이 수익의 {:.2f} % 를 차지합니다.".format(ck2))

oln1.plot(x='invoicedate', y='spent', color='tomato', figsize=(25, 16))

plt.title("spent price per date", fontsize=25)
plt.xlabel("date")
plt.ylabel("spent price")

plt.show()

res2 = oln1.drop_duplicates(['invoiceno'], keep='first')

g1 = res2[['weekday', 'invoiceno']].groupby(['weekday']).count().plot(kind='bar', figsize=(13, 6))

g1.set_ylabel("invoices' number", fontsize=12)
g1.set_title("invoices' number per weekday", fontsize=19)
g1.set_xticklabels(("Mon", "Tue", "Wed", "Thur", "Fri", "Sat", "Sun"), rotation=0, fontsize=12)

plt.show()

res3=res2[['hour', 'invoiceno']].groupby(['hour']).count()

g2 =res3.plot(kind='bar', color='orange', figsize=(13, 6))

g2.set_ylabel("invoices' number", fontsize=13)
g2.set_title("invoices' number per hour", fontsize=19)
plt.xticks(rotation=0)

plt.show()

res4 = oln1[['quantity', 'spent', 'country', 'invoiceno']]
res4

aa = res4.groupby(['country', 'invoiceno']).sum()
aa['count']=1
aa

bb = aa.groupby('country').sum()
bb

bb['average_spent']=bb['spent']/bb['count']
bb.sort_values(['count', 'average_spent'], ascending=False, inplace=True)
bb.head()

color=plt.cm.viridis(np.linspace(0, 1, 38))
bb['average_spent'].sort_values().plot(kind='barh', figsize=(12, 9), color=color)
plt.title("Average sales per country's single invoice", size=19)
plt.xlabel('sales', size=15)

from wordcloud import WordCloud
from wordcloud import STOPWORDS

stopwords = set(STOPWORDS)
wordcloud = WordCloud(stopwords=stopwords, background_color='black', width=800, height=600, colormap='PuBu').generate(str(oln1['description']))
plt.axis('off')
plt.imshow(wordcloud)
